//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Sig2.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_THREADLIST                  101
#define IDC_SCHEDULELIST                102
#define ID_INDICATOR_THREADS            103
#define ID_INDICATOR_SCHEDULES          104
#define ID_INDICATOR_ICON               105
#define ID_TMR_STATS                    106
#define IDR_MAINFRAME                   128
#define IDR_THREADBAL_ENG               128
#define IDR_MENU_ENG                    128
#define IDR_THREADBAL_CHS               129
#define IDR_SCHBAL_CHS                  130
#define IDR_SCHBAL_ENG                  131
#define IDR_MENU_CHS                    132
#define IDB_HEADS                       134
#define IDB_ITEM                        135
#define IDD_GLOBAL                      136
#define IDD_PAGE_NAME                   138
#define IDD_PAGE_D2EXE                  139
#define IDI_ICON1                       140
#define IDD_PAGE_GAME                   140
#define IDD_PAGE_HACK                   141
#define IDD_PAGE_D2H                    142
#define IDD_PAGE_JSP                    143
#define IDD_PAGE_FINISH                 144
#define IDD_PAGE_LOGIN                  145
#define IDD_PAGE_MULE                   146
#define IDD_ACCOUNTDLG                  147
#define IDD_PAGE_SELTYPE                149
#define IDI_ICON2                       149
#define IDD_PAGE_SCHNAME                150
#define IDD_PAGE_SCHDATA                151
#define IDD_SCHDLG                      152
#define IDR_TOOLBAR1                    158
#define IDD_DLGDLG                      160
#define IDR_POPUP_CHS                   161
#define IDD_STATSDLG                    163
#define IDD_PAGE_THREADTYPE             164
#define IDD_REALMDLG                    165
#define IDD_REALMEDITDLG                166
#define IDD_PAGE_SCHREPEAT              167
#define IDR_POPUP_ENG                   167
#define IDC_LBL_GAMES                   1000
#define IDC_LBL_DELAYS                  1001
#define IDC_LBL_MAXD2                   1002
#define IDC_LBL_LAUNCH                  1003
#define IDC_LBL_LOGIN                   1004
#define IDC_LBL_CHARSEL                 1005
#define IDC_ACCOUNT                     1005
#define IDC_LBL_CREATE                  1006
#define IDC_PASSWORD                    1006
#define IDC_LBL_CONNECT                 1007
#define IDC_REPEATPASSWORD              1007
#define IDC_LBL_RND                     1008
#define IDC_LAUNCHDELAY                 1010
#define IDC_LOGINDELAY                  1011
#define IDC_CHARSELDELAY                1012
#define IDC_JOINDELAY                   1013
#define IDC_RND1                        1014
#define IDC_ERRORDELAY                  1015
#define IDC_BTNDELAY                    1016
#define IDC_MINCONN                     1017
#define IDC_RND2                        1018
#define IDC_LBL_CLOSE                   1019
#define IDC_SPIN1                       1020
#define IDC_PREFIX                      1020
#define IDC_LBL_2GAMES                  1021
#define IDC_LBL_BTN                     1021
#define IDC_2GAMES                      1022
#define IDC_EDIT1                       1024
#define IDC_BUTTON1                     1025
#define IDC_STARTPARA2                  1025
#define IDC_SERVER                      1025
#define IDC_RADIO1                      1026
#define IDC_SUB                         1026
#define IDC_RADIO2                      1027
#define IDC_RADIO3                      1028
#define IDC_NEXT                        1028
#define IDC_RADIO4                      1029
#define IDC_JSPPATH                     1029
#define IDC_P4                          1030
#define IDC_MAXINGAME                   1030
#define IDC_STOPCOND3                   1030
#define IDC_P5                          1031
#define IDC_STOPCOND1                   1031
#define IDC_P6                          1032
#define IDC_STOPPARA1                   1032
#define IDC_P7                          1033
#define IDC_STOPPARA2                   1033
#define IDC_P8                          1034
#define IDC_P1                          1035
#define IDC_P2                          1036
#define IDC_REALMS                      1037
#define IDC_ANTIIDLE                    1038
#define IDC_REALMEDIT                   1038
#define IDC_REALMREFRESH                1039
#define IDC_LIST1                       1039
#define IDC_P3                          1040
#define IDC_CHANNEL                     1041
#define IDC_HACKITPATH                  1042
#define IDC_HACKITURL                   1043
#define IDC_JSPURL                      1044
#define IDC_LBL_PATH                    1045
#define IDC_CHECK1                      1046
#define IDC_BACK                        1047
#define IDC_COMBO1                      1049
#define IDC_STARTCOND1                  1050
#define IDC_STARTCOND2                  1051
#define IDC_STARTCOND3                  1052
#define IDC_STOPCOND2                   1053
#define IDC_STARTPARA1                  1054
#define IDC_VER                         1055
#define IDC_FRA_REALM                   1056
#define IDC_FRA_ACCOUNT                 1057
#define IDC_LBL_ACCOUNT                 1058
#define IDC_LBL_PWD                     1059
#define IDC_LBL_PWD2                    1060
#define IDC_BNETIP                      1061
#define IDC_PREFERRED                   1062
#define IDC_FRA_CHAR                    1063
#define IDC_LBL_PLAYS                   1064
#define IDC_LBL_D2EXE                   1065
#define IDC_LBL_PARAM                   1066
#define IDC_LBL_TEXT                    1067
#define IDC_DEFAULT                     1068
#define IDC_TEXT                        1068
#define IDC_LBL_CHANNEL                 1069
#define IDC_LBL_DIFFICULTY              1070
#define IDC_ADD                         1071
#define IDC_LBL_MAXSTAY                 1071
#define IDC_EDIT                        1072
#define IDC_CHARCOUNT                   1072
#define IDC_LBL_D2H                     1072
#define IDC_REMOVE                      1073
#define IDC_LBL_JSP                     1073
#define IDC_DELETE                      1073
#define IDC_LBL_CHARPOS                 1074
#define IDC_LBL_LIST                    1075
#define IDC_LBL_GAMELEN                 1076
#define IDC_LBL_NAME                    1077
#define IDC_NAMETYPE                    1077
#define IDC_LBL_TEXT1                   1078
#define IDC_RADIO5                      1078
#define IDC_LBL_TEXT2                   1079
#define IDC_RADIO6                      1079
#define IDC_LBL_THREAD                  1080
#define IDC_RADIO8                      1080
#define IDC_LBL_START                   1081
#define IDC_LBL_STOP                    1082
#define IDC_NORMAL                      1083
#define IDC_MULE                        1084
#define IDC_COPY                        1085
#define IDC_LBL_LIMIT                   1086
#define IDC_FRA_NAME                    1087
#define IDC_FRA_PWD                     1088
#define IDC_LBL_EDIT                    1089
#define IDC_MULECHARSTAYLENGTH          1094
#define IDC_FRA_APPLICATION             1094
#define IDC_LBL_TOTALRUN                1095
#define IDC_LBL_INGAME                  1096
#define IDC_LBL_CRASHES                 1097
#define IDC_FRA_GAME                    1098
#define IDC_LBL_GAMEOKS                 1100
#define IDC_MOVEUP                      1101
#define IDC_LBL_CURGAME                 1101
#define IDC_MOVEDOWN                    1102
#define IDC_LBL_ASOF                    1102
#define IDC_SINCE                       1103
#define IDC_ASOF                        1104
#define IDC_RUNNING                     1105
#define IDC_LBL_MAXGAME                 1106
#define IDC_LBL_MINGAME                 1107
#define IDC_LBL_AVERAGEGAME             1108
#define IDC_LBL_SINCE                   1109
#define IDC_FRA_GAMES                   1110
#define IDC_MINTIME                     1111
#define IDC_FRA_PLUGIN                  1112
#define IDC_FRA_BAN                     1113
#define IDC_STOP                        1114
#define IDC_SUCCESS                     1115
#define IDC_RETRY                       1115
#define IDC_CREATION                    1116
#define IDC_SWITCH                      1116
#define IDC_BANRETRY                    1117
#define IDC_MAX                         1118
#define IDC_MIN2GAMES                   1118
#define IDC_MIN                         1119
#define IDC_LBL_SERVER                  1119
#define IDC_AVG                         1120
#define IDC_LBL_SUB                     1120
#define IDC_CRASHES                     1121
#define IDC_NAME                        1121
#define IDC_CUR                         1122
#define IDC_FRA_REPEAT                  1122
#define IDC_INGAME                      1123
#define IDC_RPT                         1123
#define IDC_FIXEDPWD                    1140
#define IDC_USEFIXPWD                   1141
#define IDC_RADIO7                      1142
#define IDC_MAXD2PROC                   1151
#define ID_START                        32771
#define ID_PAUSE                        32772
#define ID_STOP                         32773
#define ID_KILL                         32774
#define ID_MULEMODE                     32775
#define ID_SHOWD2WND                    32776
#define ID_VIEWLOG                      32777
#define ID_LOG_CURRENT                  32778
#define ID_LOG_SELECT                   32779
#define ID_NEW                          32780
#define ID_DELETE                       32781
#define ID_CONFIG                       32782
#define ID_GLOBAL                       32783
#define ID_SCH_DELETE                   32792
#define ID_SCH_NEW                      32793
#define ID_SCH_CONFIG1                  32794
#define ID_VIEW_SCHEDULES               32798
#define ID_VIEW_THREADS                 32802
#define ID_LANG_CHS                     32803
#define ID_LANG_ENG                     32804
#define ID_VIEW_THREADS1                32805
#define ID_VIEW_SCHEDULES1              32806
#define ID_NEW1                         32807
#define ID_DELETE1                      32808
#define ID_CONFIG1                      32809
#define ID_START1                       32810
#define ID_PAUSE1                       32811
#define ID_STOP1                        32812
#define ID_SHOWD2WND1                   32813
#define ID_KILL1                        32814
#define ID_SCH_NEW1                     32815
#define ID_SCH_DELETE1                  32816
#define ID_SCH_CONFIG                   32817
#define ID_SCH_START                    32818
#define ID_SCH_PAUSE                    32819
#define ID_SCH_STOP                     32820
#define ID_SCH_START1                   32821
#define ID_SCH_PAUSE1                   32822
#define ID_SCH_STOP1                    32823
#define ID_VIEWLOG1                     32824
#define ID_GLOBAL1                      32825
#define ID_APP_ABOUT1                   32826
#define ID_HELP_CONTENT                 32827
#define ID_SEL_LOG                      32828
#define ID_VIEW_TOOLBAR1                32831
#define ID_HIDEWND1                     32834
#define ID_HIDEWND                      32836
#define ID_OPT_DICTIONARY               32837
#define ID_OPT_DICTIONARY1              32838
#define ID_SEL_LOG1                     32846
#define ID_POPUP_SHOWSIG                32850
#define ID_POPUP_HIDESIG                32851
#define ID_THREAD_LOG                   32856
#define ID_THREAD_LOG1                  32857
#define ID_THREAD_STATISTICS            32858
#define ID_THREAD_STATISTICS1           32859
#define ID_CUS_LOG1                     32860
#define ID_CUS_LOG2                     32861
#define ID_CUS_LOG3                     32862
#define ID_CUS_LOG4                     32863
#define ID_SEL_CUSTLOG                  32864
#define ID_SEL_CUSTLOG1                 32865
#define ID_CUS_LOG11                    32866
#define ID_CUS_LOG41                    32869
#define ID_CUS_LOG21                    32870
#define ID_CUS_LOG31                    32871
#define ID_BUTTON32876                  32876
#define ID_LEAVEGAME                    32877
#define ID_LEAVEGAME1                   32879

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32880
#define _APS_NEXT_CONTROL_VALUE         1124
#define _APS_NEXT_SYMED_VALUE           123
#endif
#endif
